version: '3.8'

services: 
  web: 
    build: .
    command: python manage.py runserver
    volumes:
    port:
    depends_on: 
      - redis
      - celery_worker
  
  redis:
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A Chatterbox worker --loglevel-info
    depends_on: 
      - redis
    
    environment:
      CELERY_BROKER_URL = redis://redis:6379/0
      CELERY_RESULT_BACKEND = redis://redis:6379/0
    